registry_collector_auth:
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 9182:9182/tcp
    - 27017:27017/tcp
  links:
    - registry:registry
  image: <image_prefix>/registry_collector_auth:v1.0.2.105.106
  volumes:
    - <configPath>/registry_collector/config.conf:/opt/source/frame/conf/config.conf
    - <configPath>/registry_collector/dbconf/mongodb_linux.conf:/opt/source/mongodb/conf/mongodb_linux.conf
    - <configPath>/nginx_conf/ssl_auth:/opt/source/frame/ssl
    - <configPath>/nginx_conf:/opt/source/frame/nginx_conf
    - <configPath>/registry_collector/hosts:/etc/hosts
    - <storagePath>/registry_collector/mongodb/data:/opt/mongodb/data
    - <storagePath>/registry_collector/logs/operation.log:/opt/source/Trace/logs/web.log
    - <storagePath>/registry_collector/repository:/opt/source/repository
    - <storagePath>/registry_collector/logs/wwwroot:/opt/wwwroot
    - <storagePath>:/.hidden/root
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc:/host/proc
    - /etc/localtime:/etc/localtime
registryui:
  restart: always
  stdin_open: true
  tty: true
  ports:
    - <UI_PORT>:80/tcp
    - <SSL_PORT>:443/tcp
  links:
    - registry:registry
  image: <image_prefix>/registry_ui:v1.0.2.104.094
  volumes:
    - <configPath>/nginx_conf:/etc/nginx/conf.d
    - /etc/localtime:/etc/localtime
registry:
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 5002:5002/tcp
  image: <image_prefix>/registry:v1.0.2.104.240
  volumes:
    - <configPath>/registry/config.yml:/etc/docker/registry/config.yml
    - <configPath>/nginx_conf/ssl_auth:/ssl
    - <storagePath>/registry/storage:/var/lib/registry
    - /etc/localtime:/etc/localtime
elasticsearch:
  restart: always
  stdin_open: true
  tty: true
  image: <image_prefix>/elasticsearch:v1.0.2.104.08
  volumes:
    - <configPath>/docker_el/elasticsearch/config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
    - <storagePath>/docker_el/elasticsearch/storage:/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  restart: always
  stdin_open: true
  tty: true
  image: <image_prefix>/logstash:v1.0.2.104.08
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - <configPath>/docker_el/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    - <storagePath>/registry_collector/logs/operation.log:/usr/share/logstash/log/collector_auth_operation.log
    - /etc/localtime:/etc/localtime
  links:
    - elasticsearch:elasticsearch
    - registry_collector_auth:registry_collector_auth
