mongodb:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  image:  <image_prefix>/mongodb:v1.0.3.110
  command: /mongodb/mongodb/bin/mongod -f /mongodb/conf/mongodb_linux.conf --dbpath /mongodb/data/db
  volumes:
    - <storagePath>/registry_collector/mongodb/data/log/trace:/mongodb/data/log/trace
    - <storagePath>/registry_collector/mongodb/data/db:/mongodb/data/db:rw
    - <configPath>/registry_collector/dbconf/mongodb_linux.conf:/mongodb/conf/mongodb_linux.conf
    - /etc/localtime:/etc/localtime:ro
registry_collector_auth:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  links:
    - mongodb:mongodb
  image: <image_prefix>/registry_collector_auth:v1.0.3.110
  volumes:
    - <configPath>/registry_collector/config.conf:/opt/source/frame/conf/config.conf:rw
    - <configPath>/nginx_conf/ssl_auth:/opt/source/frame/ssl:rw
    - <configPath>/nginx_conf:/opt/source/frame/nginx_conf:rw
    - <storagePath>/registry_collector/Trace/:/opt/source/Trace:rw
    - <storagePath>/registry_collector/repository:/opt/source/repository:rw
    - <storagePath>/registry_collector/wwwroot:/opt/wwwroot:rw
    - <storagePath>:/.hidden/root:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /proc:/host/proc:ro
    - /etc/localtime:/etc/localtime:ro
registryui:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  ports:
    - <UI_PORT>:80
    - <SSL_PORT>:443
  links:
    - elasticsearch:elasticsearch
    - registry_collector_auth:collectorauth
  image: <image_prefix>/registry_ui:v1.0.3.110
  volumes:
    - <configPath>/nginx_conf/ssl_auth:/etc/nginx/conf.d/ssl_auth
    - <configPath>/nginx_conf/docker_registry.conf:/etc/nginx/conf.d/docker_registry.conf
    - <configPath>/nginx_conf/registry_ui.conf:/etc/nginx/conf.d/registry_ui.conf
    - <configPath>/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    - /etc/localtime:/etc/localtime:ro
registry:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 5002:5002
  links:
    - registryui:registryui
    - registry_collector_auth:collector_auth
  image: <image_prefix>/registry:v1.0.3.110
  volumes:
    - <configPath>/registry/config.yml:/etc/docker/registry/config.yml:ro
    - <configPath>/nginx_conf/ssl_auth:/ssl:ro
    - <storagePath>/registry/storage:/var/lib/registry:rw
    - /etc/localtime:/etc/localtime:ro
elasticsearch:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  image: <image_prefix>/elasticsearch:v1.0.3.110
  volumes:
    - <configPath>/docker_el/elasticsearch/config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
    - <storagePath>/docker_el/elasticsearch/storage:/elasticsearch/data:rw
    - /etc/localtime:/etc/localtime:ro
logstash:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  image: <image_prefix>/logstash:v1.0.3.110
  command: logstash -f /logstash/configurations/logstash.conf
  volumes:
    - <configPath>/docker_el/logstash/config/logstash.conf:/logstash/configurations/logstash.conf
    - <storagePath>/registry_collector/Trace/logs/web.log:/logstash/log/collector_auth_operation.log
    - /etc/localtime:/etc/localtime:ro
  links:
    - elasticsearch:elasticsearch
    - registry_collector_auth:registry_collector_auth
