registry_collector_auth:
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 9182:9182/tcp
    - 27017:27017/tcp
  image: registry_collector_auth:v1.0.0.095
  volumes:
    - <configPath>/registry_collector/config.conf:/opt/source/frame/conf/config.conf
    - <configPath>/registry_collector/dbconf/mongodb_linux.conf:/opt/source/mongodb/conf/mongodb_linux.conf
    - <configPath>/nginx_conf/ssl_auth:/opt/source/frame/ssl
    - <configPath>/registry_collector/hosts:/etc/hosts
    - <storagePath>/registry_collector/mongodb/data:/opt/mongodb/data
    - <storagePath>/registry_collector/logs/operation.log:/opt/source/Trace/logs/web.log
    - <storagePath>:/.hidden/root:ro
    - /proc:/host/proc:ro
    - /etc/localtime:/etc/localtime:ro
registryui:
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 80:80/tcp
    - 443:443/tcp
  links:
    - registry:registry
  image: index.alauda.cn/cloudsoar/registry_ui:0.8.4
  volumes:
    - <configPath>/nginx_conf:/etc/nginx/conf.d
registry:
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 5002:5002/tcp
  image: index.alauda.cn/cloudsoar/registry:2.3.0
  volumes:
    - <configPath>/registry/config.yml:/etc/docker/registry/config.yml
    - <configPath>/nginx_conf/ssl_auth:/ssl
    - <storagePath>/registry/storage:/var/lib/registry
elasticsearch:
  restart: always
  stdin_open: true
  tty: true
  image: index.alauda.cn/cloudsoar/elasticsearch:0.8
  volumes:
    - <configPath>/docker_el/elasticsearch/config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
    - <storagePath>/docker_el/elasticsearch/storage:/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  restart: always
  stdin_open: true
  tty: true
  image: index.alauda.cn/cloudsoar/logstash:0.8
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - <configPath>/docker_el/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    - <storagePath>/registry_collector/logs/operation.log:/usr/share/logstash/log/collector_auth_operation.log
  links:
    - elasticsearch
    - registry_collector_auth
