mongodb:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 27017:27017
  image:  <image_prefix>/mongodb:v1.0.2.107
  command: mongod -f /data/conf/mongo.conf --dbpath /data/db
  volumes:
    - <storagePath>/mongodb/data:/data
    - <storagePath>/mongodb/data/db:/data/db
    - /etc/localtime:/etc/localtime:ro
registry_collector_auth:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 9182:9182
  links:
    - registry:registry
    - mongodb:mongodb
  image: <image_prefix>/registry_collector_auth:v1.0.2.107
  volumes:
    - <configPath>/registry_collector/config.conf:/opt/source/frame/conf/config.conf:rw
    - <configPath>/nginx_conf/ssl_auth:/opt/source/frame/ssl:rw
    - <configPath>/nginx_conf:/opt/source/frame/nginx_conf:rw
    - <storagePath>/registry_collector/logs/operation.log:/opt/source/Trace/logs/web.log:rw
    - <storagePath>/registry_collector/repository:/opt/source/repository:rw
    - <storagePath>/registry_collector/logs/wwwroot:/opt/wwwroot:rw
    - <storagePath>:/.hidden/root:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /proc:/host/proc:ro
    - /etc/localtime:/etc/localtime:ro
registryui:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  ports:
    - <UI_PORT>:80
    - <SSL_PORT>:443
  links:
    - registry:registry
  image: <image_prefix>/registry_ui:v1.0.2.107
  volumes:
    - <configPath>/nginx_conf:/etc/nginx/conf.d
    - /etc/localtime:/etc/localtime:ro
registry:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  ports:
    - 5002:5002
  image: <image_prefix>/registry:v1.0.2.107
  volumes:
    - <configPath>/registry/config.yml:/etc/docker/registry/config.yml:ro
    - <configPath>/nginx_conf/ssl_auth:/ssl:ro
    - <storagePath>/registry/storage:/var/lib/registry:rw
    - /etc/localtime:/etc/localtime:ro
elasticsearch:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  image: <image_prefix>/elasticsearch:v1.0.2.107
  volumes:
    - <configPath>/docker_el/elasticsearch/config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml:ro
    - <storagePath>/docker_el/elasticsearch/storage:/elasticsearch/data:rw
  ports:
    - "9200:9200"
logstash:
  privileged: true
  restart: always
  stdin_open: true
  tty: true
  image: <image_prefix>/logstash:v1.0.2.107
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - <configPath>/docker_el/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    - <storagePath>/registry_collector/logs/operation.log:/usr/share/logstash/log/collector_auth_operation.log:rw
    - /etc/localtime:/etc/localtime:ro
  links:
    - elasticsearch:elasticsearch
    - registry_collector_auth:registry_collector_auth
